import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <nav className="p-4 sm:p-8 border-r border-gray-400 dark:border-gray-800">
            <Link href="/">
              <Image
                className="mb-6 inline-block relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
                src="/next.svg"
                alt="Next.js Logo"
                width={180}
                height={37}
                priority
                style={{ minWidth: 130 }}
              />
            </Link>

            <h2 className="text-lg font-semibold mb-2">Server Actions</h2>

            <Link className="block underline" href="/counter">
              Counter
            </Link>
          </nav>

          <div className="p-4 sm:p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
