import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const navigation = [
  {
    category: 'Data Fetching',
    links: [{ title: 'Suspense', href: '/data-fetching-suspense' }]
  },
  {
    category: 'Server Actions',
    links: [
      { title: 'Counter', href: '/server-actions-counter' },
      { title: 'Form - Vanilla', href: '/server-actions-form' },
      { title: 'Form - RHF', href: '/server-actions-form-rhf' }
    ]
  },
  {
    category: 'State - Jotai',
    links: [
      { title: 'Todos', href: '/state-jotai-todos' },
      { title: 'Counter', href: '/state-jotai-counter' }
    ]
  }
];

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-main-layout">
          <nav className="border-r border-gray-300 dark:border-gray-600 h-screen overflow-y-auto hide-scrollbars">
            <Link href="/" className="block m-5 sm:m-8 ">
              <Image
                className="inline-block dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
                src="/next.svg"
                alt="Next.js Logo"
                width={180}
                height={37}
                priority
                style={{ minWidth: 130 }}
              />
            </Link>

            {navigation.map(({ category, links }) => (
              <div key={category}>
                <h2 className="font-semibold px-3 py-2 bg-gray-200 dark:bg-gray-800">{category}</h2>

                {links.map(({ title, href }) => (
                  <Link
                    key={href}
                    className="block border-b last:border-0 dark:border-gray-600 hover:text-blue-500 dark:hover:text-blue-300 px-3 py-2"
                    href={href}
                  >
                    {title}
                  </Link>
                ))}
              </div>
            ))}
          </nav>

          <div className="p-4 sm:p-8 h-screen overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
