import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid grid-cols-main-layout min-h-screen">
          <nav className="p-4 sm:p-8 border-r border-gray-400 dark:border-gray-600">
            <Link href="/">
              <Image
                className="inline-block relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
                src="/next.svg"
                alt="Next.js Logo"
                width={180}
                height={37}
                priority
                style={{ minWidth: 130 }}
              />
            </Link>

            <h2 className="text-lg font-semibold mt-6 mb-2">Data Fetching</h2>

            <Link className="block underline" href="/data-fetching-suspense">
              Suspense
            </Link>

            <h2 className="text-lg font-semibold mt-6 mb-2">Server Actions</h2>

            <Link className="block underline" href="/server-actions-counter">
              Counter
            </Link>

            <Link className="block underline" href="/server-actions-form">
              Form - Vanilla
            </Link>

            <Link className="block underline" href="/server-actions-form-rhf">
              Form - RHF
            </Link>

            <h2 className="text-lg font-semibold mt-6 mb-2">State</h2>

            <Link className="block underline" href="/state-jotai-todos">
              Todos - Jotai
            </Link>

            <Link className="block underline" href="/state-jotai-counter">
              Counter - Jotai
            </Link>
          </nav>

          <div className="p-4 sm:p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
